### ISSUE TITLE
extract ACLs from this plugin

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca-perm#2]
Note to self (@nherment)

create seneca-acl and 3rd party library

**Comment by AdrieanKhisbe** [comment]
@nherment, are you still considering this? :)

**Comment by nherment** [comment]
@AdrieanKhisbe not great but done: https://github.com/nherment/node-access-controls

**Comment by AdrieanKhisbe** [comment]
@nherment thanks for the pointer :)
